### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Tnu02** [navchandar/Naukri#14]
Hi,

Can anybody help me to setup this script !!

**Comment by navchandar** [comment]
If you have python installed, it should be fairly simple.

Instructions are available [here](https://github.com/navchandar/Naukri#installation)
Dummy username, password are added in the script which you can replace with your own credentials locally.

**Comment by Tnu02** [comment]
> If you have python installed, it should be fairly simple.
> 
> Instructions are available [here](https://github.com/navchandar/Naukri#installation)
> Dummy username, password are added in the script which you can replace with your own credentials locally.
> 

Thanks will check
