### ISSUE TITLE
Not able to login In naukri Site

### ISSUE THREAD

**Issue by Harih2i** [navchandar/Naukri#4]
Scarpping fails to load Naukri Login page site. 
Error: None of the elements found to login.(Error Follow up with code)

**Comment by navchandar** [comment]
can you share the login URL?

**Comment by Harih2i** [comment]
URL: https://www.naukri.com

**Comment by Harih2i** [comment]
URL: https://login.naukri.com/nLogin/Login.php

**Comment by Harih2i** [comment]
Any Update?

**Comment by navchandar** [comment]
This is the URL used by the script  and It works fine for me. Can you share the error message thrown? 
Or may be try again using updated ChromeDriver and latest Chrome browser?

**Comment by Harih2i** [comment]
I upgraded everything with no success. 
Attaching Error below.
![image](https://user-images.githubusercontent.com/13134808/54897826-fa008880-4eef-11e9-9619-4c2e48f20e9a.png)

**Comment by Harih2i** [comment]
If you think Driver updates will be the issue, then can you update requirements.txt w.r.t necessary packages? This may resolve our problem.

**Comment by navchandar** [comment]
Closing this items as not reproducible.
