### ISSUE TITLE
Headless ---

### ISSUE THREAD

**Issue by mayur-ml** [navchandar/Naukri#41]
Hey buddy,

Could you switch the script to run in headless mode? This will let it handle tasks like  without opening a Chrome browser. Also, people can  plan to set up a GitHub workflow for automatic profile updates every two hours with cron job.

Thanks!

**Comment by navchandar** [comment]
Hi,

Updated the script to enable headless mode. When you input username, password, you can now change `headless = True` to run the script in headless mode. 
Pull the latest version and try running it.
